---
- hosts: localhost
  connection: local
  vars_files:
    - vars/main.yml
  tasks:
    - include: dotfiles.yml
    - name: upgrade homebrew packages
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
    # Tap
    - name: ensure taps are tapped.
      homebrew_tap:
        name: '{{ item }}'
        state: present
      with_items: '{{ brew_taps }}'
    # Brew
    - name: install homebrew packages
      homebrew:
        name: '{{ brew_packages }}'
        state: present
    # Cask
    - name: install homebrew casks
      #homebrew_cask: name={{item}} state=present install_options='appdir=homebrew_cask_appdir'
      homebrew_cask:
        name: '{{ item }}'
        state: present
        install_options: force
      with_items: '{{ cask_packages }}'
    - name: upgrade homebrew casks
      homebrew_cask:
        upgrade_all: true
    # npm
    - name: install npm modules
      npm: name={{item}} global=yes
      with_items: '{{ npm_modules }}'
    - name: remove outdated brew versions from the cellar
      command: brew cleanup
